import type { Metadata } from "next";
import "./globals.css";
import Templates from "@/components/presentational/templates/Template";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="overflow-y-scroll">
      <body>
        <Templates>{children}</Templates>
      </body>
    </html>
  );
}
