import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/my/sidebar";
import { Input } from "@/components/ui/input";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className="overflow-y-scroll">
      <body>
        <div className="grid grid-cols-3">
          <header className="h-screen sticky top-0 bg-gray-100 p-5 flex justify-end z-10">
            <Sidebar />
          </header>
          <main className="p-5">{children}</main>
          <div className="h-screen sticky top-0 bg-gray-100 p-5 z-10">
            <div className="w-1/2">
              <Input placeholder="Search" />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
